name: flutter_boilerplate
description: A boilerplate project created in flutter using MobX.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# Regular dependencies are listed under dependencies:—these are packages that
# anyone using your package will also need.
dependencies:
  flutter:
    sdk: flutter

  # A powerful Http client for Dart, which supports Interceptors,
  # Global configuration, FormData, Request Cancellation, File downloading, Timeout etc.
  dio: ^4.0.6

  # NoSQL persistent embedded file system document-based database
  # for Dart VM and Flutter with encryption support.
  sembast: ^3.2.0

  # This plugin allows Flutter apps to discover network
  # connectivity and configure themselves accordingly.
  # It can distinguish between cellular vs WiFi connection.
  connectivity_plus: ^2.3.0

  # Simple direct Service Locator that allows to decouple the interface
  # from a concrete implementation and to access the concrete
  # implementation from everywhere in your App
  get_it: ^7.2.0

  # Classes and helper functions that support JSON code generation
  # via the `json_serializable` package.
  json_annotation: ^4.5.0

  # MobX is a library for reactively managing the state of your applications.
  # Use the power of observables, actions, and reactions to supercharge your Dart and Flutter apps.
  mobx: ^2.0.7+2

  # Flutter integration for MobX. It provides a set of Observer widgets
  # that automatically rebuild when the tracked observables change.
  flutter_mobx: ^2.0.6+1

  # Contains code to deal with internationalized/localized messages,
  # date and number formatting and parsing, bi-directional text,
  # and other internationalization issues.
  intl: ^0.17.0

  # Flutter plugin for reading and writing simple key-value pairs.
  # Wraps NSUserDefaults on iOS and SharedPreferences on Android.
  shared_preferences: ^2.0.15

  # Official extension image, support placeholder(loading)/ failed state, cache network, zoom/pan,
  # photo view, slide out page, editor(crop,rotate,flip), painting etc.
  extended_image: ^6.2.0

  # AutoRoute is a declarative routing solution, where everything
  # needed for navigation is automatically generated for you.
  auto_route: ^4.0.1

  # An SVG rendering and widget library for Flutter,
  # which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^1.0.3

  # Easy and Fast internationalizing and localization your Flutter Apps,
  # this package simplify the internationalizing process .
  easy_localization: ^3.0.1

  # Annotations for the freezed code-generator. This package does nothing without freezed too.
  freezed_annotation: ^2.0.3

  # Create awesome and powerful modal bottom sheets. Material, Cupertino iOS 13
  # or create your own style
  modal_bottom_sheet: ^2.0.1

  # RxDart is an implementation of the popular reactiveX api for asynchronous programming,
  # leveraging the native Dart Streams api.
  rxdart: ^0.27.3

  # Flutter plugin for launching a URL. Supports web, phone, SMS, and email schemes.
  url_launcher: ^6.1.2

  flutter_hooks: ^0.18.4

# Dependencies that are only needed in the development phase
# of the package itself are listed under dev_dependencies.
dev_dependencies:
  # Provides API to test Flutter applications that run on real devices and emulators.
  flutter_driver:
    sdk: flutter

  # AutoRoute is a declartive routing solution, where everything
  # needed for navigation is automatically generated for you.
  auto_route_generator: ^4.0.0

  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.1.10

  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.2.0

  # Code generator for MobX that adds support for annotating your code with
  # @observable, @computed, @action and also creating Store classes.
  mobx_codegen: ^2.0.6+2

  # Code generation for immutable classes that has a simple
  # syntax/API without compromising on the features.
  freezed: ^2.0.3+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
