name: flutter_boilerplate
description: A boilerplate project created in flutter using MobX.
version: 1.0.0+1

environment:
  sdk: '>=3.8.0-0 <4.0.0'

dependencies:
  # Core Flutter dependencies
  flutter:
    sdk: flutter

  # State management
  # MobX and Provider for state management
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  provider: ^6.1.5

  # Routing
  # AutoRoute for navigation
  auto_route: ^10.1.0

  # Networking
  # Dio for HTTP requests, connectivity_plus for network status
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1

  # Localization
  # easy_localization for i18n
  easy_localization: ^3.0.7

  # Dependency injection
  # get_it and injectable for DI
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Code generation
  # For code generation and serialization
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # UI & design
  # UI helpers and widgets
  flutter_gen: ^5.10.0
  gap: ^3.0.1
  overlay_support: ^2.1.0
  extended_image: ^10.0.1
  skeletonizer: ^2.0.1

  # Utilities
  # Useful utilities for app development
  rxdart: ^0.28.0
  faker: ^2.2.0
  shared_preferences: ^2.5.3
  file_picker: ^10.2.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  open_settings_plus: ^0.4.0

  # App update
  # For checking app updates
  new_version_plus:
    git:
      url: https://github.com/hussenIbrahim/new_version_plus
      ref: e0be8b3

  # Authentication & social login
  # Apple and Google sign-in
  sign_in_with_apple: ^7.0.1
  google_sign_in: ^6.3.0

  # Analytics & error reporting
  # Sentry for error tracking
  sentry_flutter: ^9.0.0
  sentry_logging: ^9.0.0

dev_dependencies:
  # Code generation tools
  build_runner: ^2.5.4
  freezed: ^3.0.6
  auto_route_generator: ^10.2.3
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  mobx_codegen: ^2.7.1
  # Testing
  flutter_driver:
    sdk: flutter
  # Monorepo management
  melos: ^6.3.3

# Flutter assets and material design
flutter:
  uses-material-design: true
  assets:
    - assets/translations/
