name: api
description: Dart package to manage API calls for Krisp.
version: 0.0.2
publish_to: 'none'

environment:
  sdk: '>=3.3.0-0 <4.0.0'

dependencies:
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  freezed_annotation: ^3.0.0
  retrofit: ^4.4.2
  rxdart: ^0.28.0
  socket_io_client: ^3.0.2

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  freezed: ^3.0.4
  retrofit_generator: ^9.1.9

flutter:
  generate: true
