import 'package:flutter/widgets.dart';

///This file is automatically generated.
/// DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();
}

extension AssetsHelper on String {
  Image get png => Image.asset(this);
}
